### ISSUE TITLE
`:throws` issue: create if not found not working

### ISSUE THREAD

**Issue by muazzam0x48** [agentlang-ai/agentlang#1495]
I want to create an entity if it doesn't exist by first querying it.

```
(entity :R {:Id {:type :Int :guid true} :X :Int})

(record :Result {:Message :String})

(dataflow
 :Test1
 {:K {:Id? 1}
  :throws
  [:not-found
   [{:R {:Id 1 :X 100}}
    {:Result {:Message "Not found"}}]]})
```
Even if I try to just create :R or just return :Result, it still doesn't work.

The error I get:
```
[
    {
        "status": "not-found",
        "result": null,
        "message": null
    }
]
```

**Comment by vijayfractl** [comment]
The semantics of `:throws` is always to re-throw an error, with a custom response. This has the consequence of rolling-back any transactions. If you want to handle the failure-condition and complete the transaction with a `ok` response, use a proper `:try` expression,

```clojure
    (dataflow
     :Test1
     [:try
      {:R {:Id? 1}}
      :not-found
      [{:R {:Id 1 :X 100}} 
       {:Result {:Message "Not found"}}]]))
```
