### ISSUE TITLE
Support for Concurrent Chat Sessions and Context Window Config

### ISSUE THREAD

**Issue by hasnainnaeem** [agentlang-ai/agentlang#1525]
## Concurrent Chat Sessions
Currently, all the conversation with an agent is cached by default. But, let's say we want to start a new chat session and save chat history for each session. This could be achieved using dataflows but a more user-friendly out-of-the-box abstraction could be introduced. Some examples of such functionality are provided below:

**Start a new chat session:**
```
curl --header "Content-Type: application/json" \
     --request POST \
     --data '{
       "Joke.Core/Session": {
         "Action": "chat",
         "ConversationId": "some new UUID", ;; optional argument, if not provided, will be autogenerated and a new chat session will be started
         "UserInstruction": "Hello, this is a new conversation. Tell me a joke!"
       }
     }' \
     http://localhost:8080/api/Joke.Core/Session
```

**Continue with a chat session:**
```
curl --header "Content-Type: application/json" \
     --request POST \
     --data '{
       "Joke.Core/Session": {
         "Action": "chat",
         "ConversationId": "some existing UUID", ;; use existing chat session 
         "UserInstruction": "Hello, this is a new conversation. Tell me a joke!"
       }
     }' \
     http://localhost:8080/api/Joke.Core/Session
```

**Fetch all messages in a chat session:**
```
curl --header "Content-Type: application/json" \
     --request POST \
     --data '{
       "Joke.Core/Session": {
         "Action": "fetch_history", ;; fetch conversation session
         "ConversationId": "some existing UUID", ;; use existing chat session 
         "UserInstruction": "Hello, this is a new conversation. Tell me a joke!"
       }
     }' \
     http://localhost:8080/api/Joke.Core/Session
```
## Context Window Config
Secondly, it'd help if we can set context window length in the config, otherwise, conversations can grow indefinitely and all chat history will be sent to LLM.

**Comment by vijayfractl** [comment]
Support for chat-sessions is implemented in https://github.com/agentlang-ai/agentlang/pull/1528. A chat session can be reset by calling the `Agentlang.Core/ResetAgentChatSessions` event.

**Comment by vijayfractl** [comment]
Closing this as feature is already implemented. @hasnainnaeem Please open a new issue if any enhancements are needed.
