### ISSUE TITLE
`openai-key`, `openai-fine-tuned-model` fields in EventContext missing 

### ISSUE THREAD

**Issue by mkazmi-twist** [agentlang-ai/agentlang#1546]
To reproduce:

Make sure you are using Cognito authentication and the user you are logging in as has fields and values for `custom:openai-key` and `custom:openai-fine-tuned-model` present on Cognito.

```
(dataflow
 :Test1
 [:eval '(println :Test1.EventContext)])
```

Invoke this dataflow that lists entire EventContext after logging in. In this case, openai- fields are always `nil`.

**Comment by vijayfractl** [comment]
@muazzam0x48 @kumarshantanu This was a read-permission issue on custom-attributes. The permission is now set in cognito. Please test and close the issue.
